bot:
  presence:
    type: PLAYING
    text: Legend of Mushroom
    status: online
countdown:
  updateInterval: 1000
  resetTime: '00:00:00'
  timezone: UTC-4
  serverName: AMEN-769
  guilds:
    '1348560897362104330':
      channelId: '1348560897362104333'
  channelId: null
welcome:
  guilds:
    '1348560897362104330':
      channelId: '1348560897362104333'
